# Generated by Django 5.0.2 on 2024-03-08 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospAdmin', '0002_alter_appointment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='doctor',
        ),
    ]
