services:
  - type: web
    name: django-app
    env: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn webAppProject.wsgi:application"
    healthCheckPath: /
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: django-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4

databases:
  - name: django-db
    databaseName: django
    user: django
    plan: free
