# Generated by Django 5.0.4 on 2024-05-06 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospAdmin', '0006_alter_appointment_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='prescription',
            field=models.CharField(choices=[('paracetamol, ibuprofen', 'Paracetamol, Ibuprofen'), ('antibiotics', 'Antibiotics'), ('antihistamines', 'Antihistamines'), ('antacids', 'Antacids'), ('anticoagulants', 'Anticoagulants'), ('antidepressants', 'Antidepressants'), ('antipsychotics', 'Antipsychotics'), ('anesthetics', 'Anesthetics'), ('antivirals', 'Antivirals'), ('bronchodilators', 'Bronchodilators'), ('contraceptives', 'Contraceptives'), ('diuretics', 'Diuretics'), ('laxatives', 'Laxatives'), ('stimulants', 'Stimulants'), ('steroids', 'Steroids'), ('muscle relaxants', 'Muscle Relaxants'), ('narcotics', 'Narcotics'), ('sedatives', 'Sedatives'), ('tranquilizers', 'Tranquilizers'), ('vaccines', 'Vaccines'), ('vitamins', 'Vitamins'), ('other', 'Other')], default='paracetamol, ibuprofen', max_length=100),
        ),
    ]
