# Generated by Django 5.0.2 on 2024-05-07 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospAdmin', '0007_session_prescription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='prescription',
        ),
    ]
