# Generated by Django 5.0.2 on 2024-05-28 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospAdmin', '0009_inventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('OUT OF STOCK', 'Out of Stock'), ('REFILL SOON', 'Refill Soon')], default='AVAILABLE', max_length=20),
        ),
    ]
