# Generated by Django 5.0.2 on 2024-05-28 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospAdmin', '0010_inventory_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='category',
            field=models.CharField(default='Medicine', max_length=100),
        ),
    ]
