# Generated by Django 5.0.2 on 2024-05-28 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospAdmin', '0011_inventory_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='price',
            field=models.FloatField(default=2500.0),
        ),
    ]
